#############################################################################
# Makefile for building: libhelloworld.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri Aug 3 11:03:46 2012
# Project:  helloworld.pro
# Template: lib
# Command: /mnt/usb/bin/qmake -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile helloworld.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/mnt/usb/mkspecs/qws/linux-arm-g++ -I. -I/mnt/usb/include/QtCore -I/mnt/usb/include/QtNetwork -I/mnt/usb/include/QtGui -I/mnt/usb/include -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/mnt/usb/lib -shared -Wl,-soname,libhelloworld.so.1
LIBS          = $(SUBLIBS)  -L/mnt/usb/lib -lQtGui -L/mnt/usb/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /mnt/usb/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = helloworld.cpp 
OBJECTS       = helloworld.o
DIST          = /mnt/usb/mkspecs/common/g++.conf \
		/mnt/usb/mkspecs/common/unix.conf \
		/mnt/usb/mkspecs/common/linux.conf \
		/mnt/usb/mkspecs/common/qws.conf \
		/mnt/usb/mkspecs/qconfig.pri \
		/mnt/usb/mkspecs/modules/qt_webkit_version.pri \
		/mnt/usb/mkspecs/features/qt_functions.prf \
		/mnt/usb/mkspecs/features/qt_config.prf \
		/mnt/usb/mkspecs/features/exclusive_builds.prf \
		/mnt/usb/mkspecs/features/default_pre.prf \
		/mnt/usb/mkspecs/features/debug.prf \
		/mnt/usb/mkspecs/features/default_post.prf \
		/mnt/usb/mkspecs/features/dll.prf \
		/mnt/usb/mkspecs/features/shared.prf \
		/mnt/usb/mkspecs/features/warn_on.prf \
		/mnt/usb/mkspecs/features/qt.prf \
		/mnt/usb/mkspecs/features/unix/thread.prf \
		/mnt/usb/mkspecs/features/moc.prf \
		/mnt/usb/mkspecs/features/resources.prf \
		/mnt/usb/mkspecs/features/uic.prf \
		/mnt/usb/mkspecs/features/yacc.prf \
		/mnt/usb/mkspecs/features/lex.prf \
		/mnt/usb/mkspecs/features/include_source_dir.prf \
		helloworld.pro
QMAKE_TARGET  = helloworld
DESTDIR       = ../
TARGET        = libhelloworld.so.1.0.0
TARGETA       = ../libhelloworld.a
TARGETD       = libhelloworld.so.1.0.0
TARGET0       = libhelloworld.so
TARGET1       = libhelloworld.so.1
TARGET2       = libhelloworld.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../$(TARGET)

../$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../ || $(MKDIR) ../ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../$(TARGET)
	-$(DEL_FILE) ../$(TARGET0)
	-$(DEL_FILE) ../$(TARGET1)
	-$(DEL_FILE) ../$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) ../



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: helloworld.pro  /mnt/usb/mkspecs/qws/linux-arm-g++/qmake.conf /mnt/usb/mkspecs/common/g++.conf \
		/mnt/usb/mkspecs/common/unix.conf \
		/mnt/usb/mkspecs/common/linux.conf \
		/mnt/usb/mkspecs/common/qws.conf \
		/mnt/usb/mkspecs/qconfig.pri \
		/mnt/usb/mkspecs/modules/qt_webkit_version.pri \
		/mnt/usb/mkspecs/features/qt_functions.prf \
		/mnt/usb/mkspecs/features/qt_config.prf \
		/mnt/usb/mkspecs/features/exclusive_builds.prf \
		/mnt/usb/mkspecs/features/default_pre.prf \
		/mnt/usb/mkspecs/features/debug.prf \
		/mnt/usb/mkspecs/features/default_post.prf \
		/mnt/usb/mkspecs/features/dll.prf \
		/mnt/usb/mkspecs/features/shared.prf \
		/mnt/usb/mkspecs/features/warn_on.prf \
		/mnt/usb/mkspecs/features/qt.prf \
		/mnt/usb/mkspecs/features/unix/thread.prf \
		/mnt/usb/mkspecs/features/moc.prf \
		/mnt/usb/mkspecs/features/resources.prf \
		/mnt/usb/mkspecs/features/uic.prf \
		/mnt/usb/mkspecs/features/yacc.prf \
		/mnt/usb/mkspecs/features/lex.prf \
		/mnt/usb/mkspecs/features/include_source_dir.prf \
		/mnt/usb/lib/libQtGui.prl \
		/mnt/usb/lib/libQtNetwork.prl \
		/mnt/usb/lib/libQtCore.prl
	$(QMAKE) -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile helloworld.pro
/mnt/usb/mkspecs/common/g++.conf:
/mnt/usb/mkspecs/common/unix.conf:
/mnt/usb/mkspecs/common/linux.conf:
/mnt/usb/mkspecs/common/qws.conf:
/mnt/usb/mkspecs/qconfig.pri:
/mnt/usb/mkspecs/modules/qt_webkit_version.pri:
/mnt/usb/mkspecs/features/qt_functions.prf:
/mnt/usb/mkspecs/features/qt_config.prf:
/mnt/usb/mkspecs/features/exclusive_builds.prf:
/mnt/usb/mkspecs/features/default_pre.prf:
/mnt/usb/mkspecs/features/debug.prf:
/mnt/usb/mkspecs/features/default_post.prf:
/mnt/usb/mkspecs/features/dll.prf:
/mnt/usb/mkspecs/features/shared.prf:
/mnt/usb/mkspecs/features/warn_on.prf:
/mnt/usb/mkspecs/features/qt.prf:
/mnt/usb/mkspecs/features/unix/thread.prf:
/mnt/usb/mkspecs/features/moc.prf:
/mnt/usb/mkspecs/features/resources.prf:
/mnt/usb/mkspecs/features/uic.prf:
/mnt/usb/mkspecs/features/yacc.prf:
/mnt/usb/mkspecs/features/lex.prf:
/mnt/usb/mkspecs/features/include_source_dir.prf:
/mnt/usb/lib/libQtGui.prl:
/mnt/usb/lib/libQtNetwork.prl:
/mnt/usb/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile helloworld.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/helloworld1.0.0 || $(MKDIR) .tmp/helloworld1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/helloworld1.0.0/ && $(COPY_FILE) --parents helloworld.h .tmp/helloworld1.0.0/ && $(COPY_FILE) --parents helloworld.cpp .tmp/helloworld1.0.0/ && (cd `dirname .tmp/helloworld1.0.0` && $(TAR) helloworld1.0.0.tar helloworld1.0.0 && $(COMPRESS) helloworld1.0.0.tar) && $(MOVE) `dirname .tmp/helloworld1.0.0`/helloworld1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/helloworld1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) ../$(TARGET) 
	-$(DEL_FILE) ../$(TARGET0) ../$(TARGET1) ../$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

helloworld.o: helloworld.cpp helloworld.h \
		../../controlpanel/plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helloworld.o helloworld.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

