#include "birdswidget.h"
#include "ui_birdswidget.h"

#include <QDebug>

#include <QGraphicsPixmapItem>

#include <qmath.h>
#include <QTime>

BirdsWidget::BirdsWidget(QWidget *parent) :
    QWidget(parent)
    , _ui(new Ui::BirdsWidget)
    , _scene(new QGraphicsScene(0, 0, 400, 300))
    , _timer(new QTimer)
    , _animationCounter(0)
{
    _ui->setupUi(this);
    qsrand(QTime::currentTime().msec());

    _ui->view->setAlignment(Qt::AlignTop | Qt::AlignLeft);
    _ui->view->setRenderHints(QPainter::Antialiasing);
    _ui->view->show();

    animate();

    _timer->setInterval(50);
    connect(_timer, SIGNAL(timeout()), this, SLOT(animate()));
    _timer->start();
}

BirdsWidget::~BirdsWidget()
{
    delete _ui;
}

void BirdsWidget::animate()
{
    _scene->clear();

    normalAnimation(_animationCounter, 33);

    _animationCounter = (++_animationCounter) % 10000;

    _ui->view->setScene(_scene);
}

void BirdsWidget::normalAnimation(unsigned int counter, int value)
{
    _scene->addPixmap(QPixmap(":/birds/images/higru.png"));

    QGraphicsPixmapItem* clouds = _scene->addPixmap(QPixmap(":/birds/images/normalclouds.png"));
    clouds->setPos(_scene->sceneRect().x() + (counter/2 % _scene->sceneRect().toRect().width()), _scene->sceneRect().y());
    QGraphicsPixmapItem* clouds2 = _scene->addPixmap(QPixmap(":/birds/images/normalclouds.png"));
    clouds2->setPos(_scene->sceneRect().x() + (counter/2 % _scene->sceneRect().toRect().width()) - _scene->sceneRect().width(), _scene->sceneRect().y());

    QPen cordPen;
    cordPen.setWidth(3);
    cordPen.setCapStyle(Qt::RoundCap);

    // front cord
    QPainterPath p1(QPointF(17, 140));
    p1.cubicTo(160, 170 + (qSin(counter/10)*4), 210, 160 + (qSin((counter+5)/10)*2), 323, 151);
    _scene->addPath(p1, cordPen);

    // rear cord
    QPainterPath p2(QPointF(72, 110));
    p2.quadTo(200, 140 + (qSin((counter+qrand()%5)/10)), 378, 120);
    _scene->addPath(p2, cordPen);

    // swing
    QPointF swingKnot1(p1.pointAtPercent(0.7));
    QPointF swingKnot2(p1.pointAtPercent(0.9));
    //_scene->addLine(swingKnot1.x(), swingKnot1.y(), swingKnot1.x(), swingKnot1.y()+50);
    //_scene->addLine(swingKnot2.x(), swingKnot2.y(), swingKnot2.x(), swingKnot2.y()+50);
    QGraphicsPixmapItem* swing = _scene->addPixmap(QPixmap(":/birds/images/swing.png"));
    swing->translate(0, ceil((swingKnot1.y() - swingKnot2.y())/2));

    QFont cFont("Arial", 25, QFont::Bold, false);
    QGraphicsTextItem* consumptionShadow = _scene->addText("0 Watt", cFont);
    consumptionShadow->setPos(ceil(swingKnot1.x()+2), ceil(swingKnot1.y() + 40+2));
    consumptionShadow->setDefaultTextColor(Qt::green);
    QGraphicsTextItem* consumption = _scene->addText("0 Watt", cFont);
    consumption->setPos(ceil(swingKnot1.x()), ceil(swingKnot1.y() + 40));
    consumption->setDefaultTextColor(Qt::white);

    _scene->addPixmap(QPixmap(":/birds/images/pillars.png"));
}

void BirdsWidget::paintEvent(QPaintEvent *)
{
    _ui->view->ensureVisible(_scene->sceneRect());
    // remove the mysterious border generated by fitInView by adjusting the sceneRect
    QRectF rect(_scene->sceneRect());
    _ui->view->fitInView(QRectF(rect.x(), rect.y(), rect.width()-6, rect.height()-6), Qt::KeepAspectRatio);
}
