#############################################################################
# Makefile for building: libdispvaluesplugin.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri Aug 3 11:03:46 2012
# Project:  dispvaluesplugin.pro
# Template: lib
# Command: /mnt/usb/bin/qmake -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile dispvaluesplugin.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/mnt/usb/mkspecs/qws/linux-arm-g++ -I. -I/mnt/usb/include/QtCore -I/mnt/usb/include/QtNetwork -I/mnt/usb/include/QtGui -I/mnt/usb/include -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/mnt/usb/lib -shared -Wl,-soname,libdispvaluesplugin.so.1
LIBS          = $(SUBLIBS)  -L/mnt/usb/lib -lQtGui -L/mnt/usb/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /mnt/usb/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/dispval.cpp \
		src/json/json.cpp \
		src/plotter/plotsettings.cpp \
		src/plotter/plotter.cpp \
		src/plotter/qpointd.cpp \
		src/spritevis/tacho.cpp \
		src/spritevis/zeiger.cpp \
		src/spritevis/qcustomgraphview.cpp moc_dispval.cpp \
		moc_plotter.cpp \
		moc_tacho.cpp \
		moc_qcustomgraphview.cpp \
		qrc_dispval.cpp \
		qrc_mice.cpp
OBJECTS       = main.o \
		dispval.o \
		json.o \
		plotsettings.o \
		plotter.o \
		qpointd.o \
		tacho.o \
		zeiger.o \
		qcustomgraphview.o \
		moc_dispval.o \
		moc_plotter.o \
		moc_tacho.o \
		moc_qcustomgraphview.o \
		qrc_dispval.o \
		qrc_mice.o
DIST          = /mnt/usb/mkspecs/common/g++.conf \
		/mnt/usb/mkspecs/common/unix.conf \
		/mnt/usb/mkspecs/common/linux.conf \
		/mnt/usb/mkspecs/common/qws.conf \
		/mnt/usb/mkspecs/qconfig.pri \
		/mnt/usb/mkspecs/modules/qt_webkit_version.pri \
		/mnt/usb/mkspecs/features/qt_functions.prf \
		/mnt/usb/mkspecs/features/qt_config.prf \
		/mnt/usb/mkspecs/features/exclusive_builds.prf \
		/mnt/usb/mkspecs/features/default_pre.prf \
		/mnt/usb/mkspecs/features/debug.prf \
		/mnt/usb/mkspecs/features/default_post.prf \
		/mnt/usb/mkspecs/features/dll.prf \
		/mnt/usb/mkspecs/features/shared.prf \
		/mnt/usb/mkspecs/features/warn_on.prf \
		/mnt/usb/mkspecs/features/qt.prf \
		/mnt/usb/mkspecs/features/unix/thread.prf \
		/mnt/usb/mkspecs/features/moc.prf \
		/mnt/usb/mkspecs/features/resources.prf \
		/mnt/usb/mkspecs/features/uic.prf \
		/mnt/usb/mkspecs/features/yacc.prf \
		/mnt/usb/mkspecs/features/lex.prf \
		/mnt/usb/mkspecs/features/include_source_dir.prf \
		dispvaluesplugin.pro
QMAKE_TARGET  = dispvaluesplugin
DESTDIR       = ../
TARGET        = libdispvaluesplugin.so.1.0.0
TARGETA       = ../libdispvaluesplugin.a
TARGETD       = libdispvaluesplugin.so.1.0.0
TARGET0       = libdispvaluesplugin.so
TARGET1       = libdispvaluesplugin.so.1
TARGET2       = libdispvaluesplugin.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../$(TARGET)

../$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../ || $(MKDIR) ../ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../$(TARGET)
	-$(DEL_FILE) ../$(TARGET0)
	-$(DEL_FILE) ../$(TARGET1)
	-$(DEL_FILE) ../$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) ../



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: dispvaluesplugin.pro  /mnt/usb/mkspecs/qws/linux-arm-g++/qmake.conf /mnt/usb/mkspecs/common/g++.conf \
		/mnt/usb/mkspecs/common/unix.conf \
		/mnt/usb/mkspecs/common/linux.conf \
		/mnt/usb/mkspecs/common/qws.conf \
		/mnt/usb/mkspecs/qconfig.pri \
		/mnt/usb/mkspecs/modules/qt_webkit_version.pri \
		/mnt/usb/mkspecs/features/qt_functions.prf \
		/mnt/usb/mkspecs/features/qt_config.prf \
		/mnt/usb/mkspecs/features/exclusive_builds.prf \
		/mnt/usb/mkspecs/features/default_pre.prf \
		/mnt/usb/mkspecs/features/debug.prf \
		/mnt/usb/mkspecs/features/default_post.prf \
		/mnt/usb/mkspecs/features/dll.prf \
		/mnt/usb/mkspecs/features/shared.prf \
		/mnt/usb/mkspecs/features/warn_on.prf \
		/mnt/usb/mkspecs/features/qt.prf \
		/mnt/usb/mkspecs/features/unix/thread.prf \
		/mnt/usb/mkspecs/features/moc.prf \
		/mnt/usb/mkspecs/features/resources.prf \
		/mnt/usb/mkspecs/features/uic.prf \
		/mnt/usb/mkspecs/features/yacc.prf \
		/mnt/usb/mkspecs/features/lex.prf \
		/mnt/usb/mkspecs/features/include_source_dir.prf \
		/mnt/usb/lib/libQtGui.prl \
		/mnt/usb/lib/libQtNetwork.prl \
		/mnt/usb/lib/libQtCore.prl
	$(QMAKE) -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile dispvaluesplugin.pro
/mnt/usb/mkspecs/common/g++.conf:
/mnt/usb/mkspecs/common/unix.conf:
/mnt/usb/mkspecs/common/linux.conf:
/mnt/usb/mkspecs/common/qws.conf:
/mnt/usb/mkspecs/qconfig.pri:
/mnt/usb/mkspecs/modules/qt_webkit_version.pri:
/mnt/usb/mkspecs/features/qt_functions.prf:
/mnt/usb/mkspecs/features/qt_config.prf:
/mnt/usb/mkspecs/features/exclusive_builds.prf:
/mnt/usb/mkspecs/features/default_pre.prf:
/mnt/usb/mkspecs/features/debug.prf:
/mnt/usb/mkspecs/features/default_post.prf:
/mnt/usb/mkspecs/features/dll.prf:
/mnt/usb/mkspecs/features/shared.prf:
/mnt/usb/mkspecs/features/warn_on.prf:
/mnt/usb/mkspecs/features/qt.prf:
/mnt/usb/mkspecs/features/unix/thread.prf:
/mnt/usb/mkspecs/features/moc.prf:
/mnt/usb/mkspecs/features/resources.prf:
/mnt/usb/mkspecs/features/uic.prf:
/mnt/usb/mkspecs/features/yacc.prf:
/mnt/usb/mkspecs/features/lex.prf:
/mnt/usb/mkspecs/features/include_source_dir.prf:
/mnt/usb/lib/libQtGui.prl:
/mnt/usb/lib/libQtNetwork.prl:
/mnt/usb/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /mnt/usb/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile dispvaluesplugin.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/dispvaluesplugin1.0.0 || $(MKDIR) .tmp/dispvaluesplugin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dispvaluesplugin1.0.0/ && $(COPY_FILE) --parents src/dispval.h src/json/json.h src/plotter/plotsettings.h src/plotter/plotter.h src/plotter/converter.h src/plotter/qpointd.h src/spritevis/tacho.h src/spritevis/zeiger.h src/spritevis/qcustomgraphview.h .tmp/dispvaluesplugin1.0.0/ && $(COPY_FILE) --parents dispval.qrc src/spritevis/mice.qrc .tmp/dispvaluesplugin1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/dispval.cpp src/json/json.cpp src/plotter/plotsettings.cpp src/plotter/plotter.cpp src/plotter/qpointd.cpp src/spritevis/tacho.cpp src/spritevis/zeiger.cpp src/spritevis/qcustomgraphview.cpp .tmp/dispvaluesplugin1.0.0/ && (cd `dirname .tmp/dispvaluesplugin1.0.0` && $(TAR) dispvaluesplugin1.0.0.tar dispvaluesplugin1.0.0 && $(COMPRESS) dispvaluesplugin1.0.0.tar) && $(MOVE) `dirname .tmp/dispvaluesplugin1.0.0`/dispvaluesplugin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dispvaluesplugin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) ../$(TARGET) 
	-$(DEL_FILE) ../$(TARGET0) ../$(TARGET1) ../$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dispval.cpp moc_plotter.cpp moc_tacho.cpp moc_qcustomgraphview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dispval.cpp moc_plotter.cpp moc_tacho.cpp moc_qcustomgraphview.cpp
moc_dispval.cpp: src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h \
		src/dispval.h
	/mnt/usb/bin/moc $(DEFINES) $(INCPATH) src/dispval.h -o moc_dispval.cpp

moc_plotter.cpp: src/plotter/plotsettings.h \
		src/plotter/converter.h \
		src/plotter/qpointd.h \
		src/plotter/plotter.h
	/mnt/usb/bin/moc $(DEFINES) $(INCPATH) src/plotter/plotter.h -o moc_plotter.cpp

moc_tacho.cpp: src/spritevis/zeiger.h \
		src/spritevis/tacho.h
	/mnt/usb/bin/moc $(DEFINES) $(INCPATH) src/spritevis/tacho.h -o moc_tacho.cpp

moc_qcustomgraphview.cpp: src/spritevis/qcustomgraphview.h
	/mnt/usb/bin/moc $(DEFINES) $(INCPATH) src/spritevis/qcustomgraphview.h -o moc_qcustomgraphview.cpp

compiler_rcc_make_all: qrc_dispval.cpp qrc_mice.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_dispval.cpp qrc_mice.cpp
qrc_dispval.cpp: dispval.qrc \
		resources/msg.png \
		resources/msg.ico
	/mnt/usb/bin/rcc -name dispval dispval.qrc -o qrc_dispval.cpp

qrc_mice.cpp: src/spritevis/mice.qrc \
		src/spritevis/images/tacho.png \
		src/spritevis/images/tacho2.png
	/mnt/usb/bin/rcc -name mice src/spritevis/mice.qrc -o qrc_mice.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: src/main.cpp src/dispval.h \
		src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h \
		../../controlpanel/plugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

dispval.o: src/dispval.cpp src/dispval.h \
		src/json/json.h \
		src/plotter/converter.h \
		src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/qpointd.h \
		src/spritevis/tacho.h \
		src/spritevis/zeiger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispval.o src/dispval.cpp

json.o: src/json/json.cpp src/json/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json.o src/json/json.cpp

plotsettings.o: src/plotter/plotsettings.cpp src/plotter/plotsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotsettings.o src/plotter/plotsettings.cpp

plotter.o: src/plotter/plotter.cpp src/plotter/plotter.h \
		src/plotter/plotsettings.h \
		src/plotter/converter.h \
		src/plotter/qpointd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotter.o src/plotter/plotter.cpp

qpointd.o: src/plotter/qpointd.cpp src/plotter/qpointd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qpointd.o src/plotter/qpointd.cpp

tacho.o: src/spritevis/tacho.cpp src/spritevis/tacho.h \
		src/spritevis/zeiger.h \
		src/spritevis/qcustomgraphview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tacho.o src/spritevis/tacho.cpp

zeiger.o: src/spritevis/zeiger.cpp src/spritevis/zeiger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zeiger.o src/spritevis/zeiger.cpp

qcustomgraphview.o: src/spritevis/qcustomgraphview.cpp src/spritevis/qcustomgraphview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomgraphview.o src/spritevis/qcustomgraphview.cpp

moc_dispval.o: moc_dispval.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dispval.o moc_dispval.cpp

moc_plotter.o: moc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotter.o moc_plotter.cpp

moc_tacho.o: moc_tacho.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tacho.o moc_tacho.cpp

moc_qcustomgraphview.o: moc_qcustomgraphview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomgraphview.o moc_qcustomgraphview.cpp

qrc_dispval.o: qrc_dispval.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dispval.o qrc_dispval.cpp

qrc_mice.o: qrc_mice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mice.o qrc_mice.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

